### ISSUE TITLE
Kapu robbanása

### ISSUE THREAD

**Issue by triszt4n** [triszt4n/unity-project#26]
A Gate jelenleg elég kicsi és nincs hozzá sprite. Kéne szerezni valami grafikát (vagy saját is OK), és nagyobb is lehetne, illetve a kapu két végében a stub-ok lehetnének ütközési pontok, így azok érintésével nem aktiválódna a kapu, csak ha a közepére megyünk, tehát a hitbox is lehet kicsit kisebb, kb vhogy így:
![image](https://user-images.githubusercontent.com/60111772/141856579-c3c24b9e-f1fe-43b6-a89d-4bf1d6094b5a.png)
A zöld rész a hitbox, amivel aktiválódik a robbanás, és a piros stub-ok, amikbe ütközni tud az űrhajó

**Comment by triszt4n** [comment]
In relation with #24

**Comment by tetsuchii** [comment]
MI lenne, ha lecserélnénk ezt a vonalat egy ilyen dimenzió átlépős kerek kapura? http://pixelartmaker.com/art/48890ee8a13e3f6
