### ISSUE TITLE
Fancy háttér

### ISSUE THREAD

**Issue by triszt4n** [triszt4n/unity-project#27]
Millióegy háttér van unity asset storeon ingyen, azok közül kéne egy űr témájú, amit be lehetne rakni (legtöbbjük még szépen világítós-színes-szagos és mozgós és animált is).

**Comment by vercibar** [comment]
https://assetstore.unity.com/packages/2d/textures-materials/deep-space-skybox-pack-11056#content

**Comment by tetsuchii** [comment]
https://assetstore.unity.com/packages/2d/textures-materials/galaxy-fire-skybox-10976
