### ISSUE TITLE
WebGL hiba: a hosszan nyomott egérgombra nem lő folyamatosan az űrhajó

### ISSUE THREAD

**Issue by triszt4n** [triszt4n/unity-project#29]

**Comment by poiuztrewq1** [comment]
Annak aki ezt elvállalja: Érdemes lenne megpróbálni a hosszan nyomott egérgombnál nem az eltelt frame-eket, hanem az össz eltelt időt(`Time.deltatime`) összegezni, vagy Coroutine-nal megoldani.
