### ISSUE TITLE
Add sound effects

### ISSUE THREAD

**Issue by poiuztrewq1** [triszt4n/unity-project#66]
- Add background music
- Add sfx for shooting
- Add sfx for explosion

See next comment for recommendations

**Comment by triszt4n** [comment]
Recommendations:
* https://www.youtube.com/watch?v=KxwUy2S2n-Q&list=PLW_omwEM1aid1jtpNhqigEcRHAVsR-Hmz
* https://www.youtube.com/watch?v=gIaDD-kqr0M

Sound effect kit:
* https://assetstore.unity.com/packages/audio/sound-fx/shooting-sound-177096 (van hangeffekt a lézerre, heal-upra)
* https://assetstore.unity.com/packages/audio/sound-fx/free-retro-sfx-pack-43256 (ez esetleg jobban illhet hozzánk, nagyon jó robbanás hangok vannak stb)
